/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Image;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.MySQL;

/**
 *
 * @author ROG STRIX
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public static int UserId;
    public static String userType;

    public LogIn() {
        initComponents();
        ImageIcon i = new ImageIcon("src/resourse/image/3.png");
        Image x = i.getImage();
        setIconImage(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jPasswordField1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial Nova", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 410, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourse/image/2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 410, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourse/image/1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextField1.getText();
        char[] pw = jPasswordField1.getPassword();
        String password = String.valueOf(pw);
        String type;

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter username", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ResultSet rs = MySQL.search("SELECT * FROM `user` INNER JOIN `user_type` ON  `user`.`user_type_id`=`user_type`.`id` WHERE `user`.`username`='" + username + "' AND `user`.`password`='" + password + "' ");
                if (rs.next()) {
                    if (rs.getString("user.status_id").equals("4")) {
                        type = rs.getString("user_type.name");
                        if (type.equalsIgnoreCase("Super Admin")) {
                            AdminPanel ap = new AdminPanel();
                            ap.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            ap.setVisible(true);
                            this.dispose();
                        } else if (type.equalsIgnoreCase("Admin")) {
                            AdminPanel ap = new AdminPanel();
                            ap.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            ap.setVisible(true);
                            this.dispose();
                        } else if (type.equalsIgnoreCase("Receptionist")) {
                            FrontDesk fd = new FrontDesk();
                            fd.setExtendedState(JFrame.MAXIMIZED_BOTH);
                            fd.setVisible(true);
                            this.dispose();

                        } else if (type.equalsIgnoreCase("Pharmacy Stock Manager")) {
                            Phamarcy p = new Phamarcy();

                            p.jPanel2.remove(p.jButton4);
                            p.setExtendedState(JFrame.MAXIMIZED_BOTH);

                            p.setVisible(true);
                            this.dispose();

                        } else if (type.equalsIgnoreCase("Pharmacy Cashier")) {
                            Phamarcy p = new Phamarcy();

                            p.jPanel2.remove(p.jButton7);
                            p.jPanel2.remove(p.jButton5);
                            p.jPanel2.remove(p.jButton3);
                            p.setExtendedState(JFrame.MAXIMIZED_BOTH);

                            p.setVisible(true);
                            this.dispose();

                        } else if (type.equalsIgnoreCase("Laboratorist")) {
                            Laboratory p = new Laboratory();
                            p.setExtendedState(JFrame.MAXIMIZED_BOTH);

                            p.setVisible(true);
                            this.dispose();

                        } else if (type.equalsIgnoreCase("Pharmacist")) {
                            Phamarcy p = new Phamarcy();
                            p.setExtendedState(JFrame.MAXIMIZED_BOTH);

                            p.setVisible(true);
                            this.dispose();

                        }
                        this.UserId = Integer.valueOf(rs.getString("user.id"));
                        this.userType = type;

                    } else {
                        JOptionPane.showMessageDialog(this, "Sorry, your account has been suspended.Please contact admin ", "Warning", JOptionPane.WARNING_MESSAGE);

                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Username or password is wrong", "Warning", JOptionPane.WARNING_MESSAGE);

                }
            } catch (Exception e) {
                e.printStackTrace();

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        InputStream is = LogIn.class.getResourceAsStream("/theam/Material Lighter.theme.json");
        IntelliJTheme.setup(is);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
